# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Page settings
title: "未踏 IoT 研究会"
email: iot@mitou.org
description: >- # this means to ignore newlines until "baseurl:"
  未踏IoT研究会は、未踏クリエイターによるIoTやスマートデバイス等の新たな分野の開拓を目指し、実践を主体とした活動を行っています。

permalink: /:title
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://iot.mitou.org" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: mitou_iot
#github_username:  mitou_iot
show_downloads: false
#google_analytics: UA-12345678-9

# Build settings
theme: jekyll-theme-slate
markdown: kramdown
plugins:
  - jekyll-feed
source:      ./
destination: ./_site
timezone: Asia/Tokyo
encoding: utf-8

highlighter: rouge
markdown: kramdown
plugins:  ['kramdown']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - Procfile
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - app.json
  - test
  - spec
